### ISSUE TITLE
Is it just for home automation?

### ISSUE THREAD

**Issue by pierreozoux** [Aldream/cozy-nest#7]
I'm actually looking for an alternative to ifttt, but I [don't care about home automation :)](https://twitter.com/internetofshit).

So do you think it is a good alternative to ifttt and hugin?

Thanks and all the best!

**Comment by benjaminplanche** [comment]
Short answer: yes but no. :-/

Yes, cause indeed, it is supposed to be generic the same way as IFTTT or Hugin.
But no, it isn't currently a good alternative. Even though I'm slowly back on it, this project is still far from being releasable.

**Comment by pierreozoux** [comment]
Thanks for your answer! Happy hacking!
